BYBIT_API_KEY = 'YjVhrEacxFQ8Ze9dgw'
BYBIT_SECRET_KEY = 'jxTKEQ6HhokJh1SJttTWZEW2CNp5oItFDHCD'

TESTNET_BYBIT_API_KEY = 'ow6UpF7syqjilE74CQ'
TESTNET_BYBIT_SECRET_KEY = 'mnbxx6hufGrr3gFLykzJKMED2nXxPabOr240'