name: trading-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - pip
  - dash=1.19.0
  - ta-lib=0.4.19
  - tornado=6.2
  - pip:
      - aiodns==3.0.0
      - aiohttp==3.8.1
      - async-timeout==4.0.1
      - attrs==21.2.0
      - bybit
      - ccxt
      - matplotlib==3.5.1
      - mplfinance==0.12.8b9
      - multidict==5.2.0
      - numpy==1.21.4
      - pandas==1.3.4
      - pandas-ta==0.3.14b0
      - pillow==9.0.1
      - requests==2.26.0
      - schedule==1.1.0
      - ta==0.8.0
      - urllib3==1.24.2
